### ISSUE TITLE
Remove attribution

### ISSUE THREAD

**Issue by tomcanac** [mongodb-js/charts-embed-sdk#12]
Wit the Iframe integration of the charts, we have the option to use attribution=false to remove mongodb logo in the chart.

Would be good to have the same option in the SDK. Currently it is not referenced, neither in the doc or the TypeScript definition.

Don't want to mess up with the content the SDK creates, and do any hacks to remove this, a native feature would be much appreciated.

Thanks!

**Comment by tomhollander** [comment]
It's there - `showAttribution` in the SDK. I'll check why it's not showing in the docs.

**Comment by tomcanac** [comment]
Good yes, It is working, thanks for setting it in the do!
