### ISSUE TITLE
How to filter using date or datetime

### ISSUE THREAD

**Issue by ppascualv** [mongodb-js/charts-embed-sdk#25]
I'm trying to use DateTime filter and it is are returning an empty chart I'm assuming the filter is not well interpreted by Mongo.

Code examples of what I already tried:
```
startDate = moment()

filter = { created_at: {
      $gte: startDate.toISOString()
}}
```

```
startDate = moment()

filter = {created_at: {
      ISODate('${endDate.format("YYYY-MM-DD")}')
}}
```

**Comment by tomhollander** [comment]
You should be able to use regular JavaScript Date objects. You don't need to format then yourself.

**Comment by kristinamongo** [comment]
An example of a filter using a JS date object:

```const filter = { created_at: { $gte: new Date('2021-03-14') } };```

This filter will return all documents that have `created_at` date of 14th of March 2021 or later.

**Comment by ppascualv** [comment]
Thanks!
