### ISSUE TITLE
Embed Dashboard Feature

### ISSUE THREAD

**Issue by zxlin** [mongodb-js/charts-embed-sdk#52]
Would it be possible embed a whole "Dashboard" rather than individual charts? Right now it looks like this only embed an individual "Chart". If I'm incorrect in this understanding, please correct me. Thanks!

**Comment by andym03** [comment]
Hi Zxlin! 

We're actually working on this feature now, and it's been suggested before! You can track progress of it [here](https://feedback.mongodb.com/forums/923524-charts/suggestions/40976389-embeded-dashboard), feel free to vote/add suggestions to this user voice page!

I'll close this suggestion for now, thanks for your interest and hope you like the feature when it's ready!

**Comment by khanguslee** [comment]
@zxlin Just a quick update, we've released embedded dashboards in [v2.2.0](https://github.com/mongodb-js/charts-embed-sdk/releases/tag/v2.2.0). Let us know how it goes 😄

**Comment by zxlin** [comment]
Thanks @khanguslee! I just saw that yesterday and will be trying it out! Thanks for the follow up!
