### ISSUE TITLE
Get list of possible filter values

### ISSUE THREAD

**Issue by abhay-agarwal** [mongodb-js/charts-embed-sdk#62]
**Is your feature request related to a problem? Please describe.**
The SDK does not have a way of returning the possible filter options, despite the Mongo Charts UI allowing the user to filter by values in a categorical field. 

**Describe the solution you'd like**
some kind of method, e.g. `getFilterValues()` to return a list of possible values. 

**Describe alternatives you've considered**
I currently manually save the filter values when generating my analytics tables internally.

**Comment by khanguslee** [comment]
Hello @abhay-agarwal! Thanks for the suggestion for the SDK. I would recommend that you submit these suggestions on the [MongoDB Feedback Engine](https://feedback.mongodb.com/forums/923524-charts). 

Upon a quick search, it looks like someone has posted a [similar suggestion](https://feedback.mongodb.com/forums/923524-charts/suggestions/43288953-get-filters-white-list-in-sdk), so I would advise that you upvote this suggestion!

**Comment by khanguslee** [comment]
Hello @abhay-agarwal!

Wanted to update you that we have just released [`v2.3.0`](https://www.npmjs.com/package/@mongodb-js/charts-embed-dom/v/2.3.0) of the SDK which includes a `getFilter()` method for both embedded dashboards and charts. 

Thanks for suggesting this feature!
