### ISSUE TITLE
Support ObjectId filter type

### ISSUE THREAD

**Issue by cesargdm** [mongodb-js/charts-embed-sdk#64]
**Is your feature request related to a problem? Please describe.**
I want to pass a ObjectId value to the `EmbedChartOptions`, if I just pass a string in the filter, I don't get the correct results since it expects an ObjectId.

**Describe the solution you'd like**
Create a `ObjectId` export or allow to parse ObjectId strings automatically.

**Additional context**
```js
{
 filter: {
  products: { $in: ['5c06e8f5b5e7d33b306f6c92'] },
}
```
> Does not work

<img width="986" alt="Screen Shot 2022-05-29 at 8 24 14 PM" src="https://user-images.githubusercontent.com/10179494/170901038-56a13599-37e3-492d-98b3-05dbdad4e253.png">

> Works

**Comment by cesargdm** [comment]
Found a solution here, maybe a helper, would be useful, or at least some documentation https://stackoverflow.com/questions/67431949/how-to-filter-mongodb-charts-with-objectid

**Comment by kristinamongo** [comment]
Hello @cesargdm, the `filter` option in `EmbedChartOptions` and the `setFilter` method in the SDK support all BSON types. This documentation is not directly related to Charts as it is a MongoDB thing. It is documented in multiple places, including here:  https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#mongodb-bsontype-ObjectId

Another way you can use bson types in your app is to import the npm `bson` library and use the `ObjectId` class - this will also allow you to create valid objectIds in your code (if you need them).

Thank you for the feedback, we can include bson type filters in our examples of how to use the SDK.

**Comment by cesargdm** [comment]
Got it, thank you @kristinamongo !
