### ISSUE TITLE
Toggle Data Value Labels & Markers programatically

### ISSUE THREAD

**Issue by jakubprogramming** [mongodb-js/charts-embed-sdk#65]
**Is your feature request related to a problem? Please describe.**
When embedded line charts are used together with filters (eg. date filters) the amount of data points rendered can vary by a lot. 
When a chart only renders data for a single day, it may be nice and helpful to have data value labels & markers to better understand the data quickly. When the date range is changed to say an entire month and much more data points are rendered, those data value labels & markers are rendered on top of each other. The only solution right now seems to be to completely disable labels and markers. Otherwise it is not practical to render large amounts of data in line charts. 

**Describe the solution you'd like**
I'd like to be able to pass a boolean value into the chart that will decide whether or not data value labels are supposed to be rendered or not. The same for markers. I imagine it working the same way the showAttribution boolean is implemented. 

**Describe alternatives you've considered**
The only workaround that I could think of right now is to configure the exact same line chart twice. Once with labels and markers and once without. Depending on the filters that are used, either one of those charts could be rendered. This would work but it would not be a clean solution in my opinion. 

**Additional context**
Take a look at these two screenshots to better understand what I mean:
![Screenshot 2022-06-08 at 12 10 54](https://user-images.githubusercontent.com/9266521/172591882-b45ab555-881d-4120-aab4-ce7d24810e03.png)
![Screenshot 2022-06-08 at 12 11 12](https://user-images.githubusercontent.com/9266521/172591900-b906687c-851c-4871-83f0-5b9ec1ca63c8.png)

**Comment by kristinamongo** [comment]
Hi @jakubprogramming. Apologies for the late reply. We are currently working on providing different customisation options for the embedded charts and data value labels and markers are included. This will most probably come in the SDK next release, will update you once this is released.

**Comment by jakubprogramming** [comment]
Hi @kristinamongo, thank you for the update. Looking forward to hearing from you again and trying out this new feature.

**Comment by kristinamongo** [comment]
Hi @jakubprogramming. The newest SDK package version 3.2.0 do have the functionality to apply customisations on embedded charts including switching off/on data markers on the charts and many more customisations. Here is a [link](https://github.com/mongodb-js/charts-embed-sdk/blob/master/docs/rendering-spec.md) to the documentation.

**Comment by jakubprogramming** [comment]
Awesome! It works very nicely and allows me to get rid of my hacky workaround where I was using two different versions of my chart. Thanks for this update!
