### ISSUE TITLE
Customize charts

### ISSUE THREAD

**Issue by tarilo** [mongodb-js/charts-embed-sdk#66]
We are integrating charts on react saas platform.

We need to customize font style and size for each charts.

We use the sdk and insert chart, no dashboard, to allow to send filters.

It's possible to change font family to get the same aspect like our SaaS?

**Comment by shaketbaby** [comment]
Sorry, this is not possible at the moment.

**Comment by tomhollander** [comment]
Closing issue; please use feedback.mongodb.com to request new features.
