### ISSUE TITLE
I am not able to embed the dashboard

### ISSUE THREAD

**Issue by ummershervani** [mongodb-js/charts-embed-sdk#68]
**Is your feature request related to a problem? Please describe.**
My goal is to create chart in Mongo DB Charts UI and show the same in UI but that's not working

**Describe the solution you'd like**
  const dashboard = sdk.createDashBoard({
    dashBoardId: "48043c78-f1d9-42ab-a2e1-f2d3c088f864"
  });
  await dashboard.render(document.getElementById("dashboard"));

**Describe alternatives you've considered**
Its very painful to do this , we will need to just show all the charts

**Additional context**

**Comment by tomhollander** [comment]
Hi @ummershervani, can you clarify what behaviour or errors you are seeing when you try to embed your dashboard?

**Comment by shaketbaby** [comment]
I noticed there are some typos in the codes, it should be a lowercase `b` in `sdk.createDashboard` and `dashboardId`.

**Comment by khanguslee** [comment]
@ummershervani Closing this issue as we believe this has been resolved in the [comment above](https://github.com/mongodb-js/charts-embed-sdk/issues/68#issuecomment-1170525348). Feel free to reopen (or open a new issue) if you reach any new problems!
