### ISSUE TITLE
Support filter in Dashboard constructor

### ISSUE THREAD

**Issue by membla** [mongodb-js/charts-embed-sdk#72]
Dashboard embed should, much like Charts, support a `filter` parameter in the constructor. The filter should then be applied to all DashboardChart instances when created.

**Comment by mongo-J** [comment]
Thanks for the feedback @membla, Embed dashboard filter is on our agenda and we are looking to make it available in the coming releases. For now `setFilter` function can be called on each individual DashboardChart to apply filter to the DashboardChart instance.

**Comment by membla** [comment]
> Thanks for the feedback @membla, Embed dashboard filter is on our agenda and we are looking to make it available in the coming releases. For now `setFilter` function can be called on each individual DashboardChart to apply filter to the DashboardChart instance.

This is what we we do now but it's less than ideal as we have not found a way to intercept the initial DashboardChart data loading and rendering so it will always show the unfiltered data first. Maybe you know of a way around that?

**Comment by mongo-J** [comment]
> This is what we we do now but it's less than ideal as we have not found a way to intercept the initial DashboardChart data loading and rendering so it will always show the unfiltered data first. Maybe you know of a way around that?

Ahh I see, a few workarounds I can think of which you may have already tried and also may not be suitable for your use case:
- Use css/javascript to hide the container where the dashboard is rendered until setFilter is completed.
- Use embed chart sdk to embed each chart individually from the dashboard, then you can utilise the `filter` option
- Apply the filter from private dashboard using filter or query bar: https://www.mongodb.com/docs/charts/filter-chart-results/, again this might not be desired depending on your use case.

**Comment by ThiagoPereiraUFV** [comment]
Any updates about this? My dev team was searching for this feature lol

**Comment by mongo-J** [comment]
> Any updates about this? My dev team was searching for this feature lol
@ThiagoPereiraUFV , thanks for reaching out, this feature has been scoped, we will provide more update on the timeline when it's available.

**Comment by mongo-J** [comment]
@membla @ThiagoPereiraUFV, thanks for waiting, we have released SDK 3.0.0 which has added support to define embed dashboard filter on initialisation, as well as setter and getter functions. Note that similar to chart filter, you would need to add the fields you wish to filter on to the allowed filter fields in side the Atlas Charts UI in the dashboard embedding dialog. Will close this issue now. 

**Release notes**: https://github.com/mongodb-js/charts-embed-sdk/releases
**Npm link**: https://www.npmjs.com/package/@mongodb-js/charts-embed-dom/v/3.0.0
**Charts doc**: https://www.mongodb.com/docs/charts/filter-embedded-dashboards/

**Comment by ThiagoPereiraUFV** [comment]
Thank you so much @mongo-J, I'm looking forward to test this feature and give some feedback. All the best!
