### ISSUE TITLE
Is it possible to have the charts in dashboard responsive? 

### ISSUE THREAD

**Issue by paufar** [mongodb-js/charts-embed-sdk#75]
I have an issue when resizing my application and i'm embedding dashboards, the charts do not break on a new line but rather cut out the text and make the width of the chart smaller.

Ideally the charts would stack beneath each other by specifying a min width for the charts so all data is visible

**Comment by tomhollander** [comment]
Today, the charts within an embedded dashboard are not responsive. You can build your own responsive behaviour if you embed the charts individually (vs the dashboard).

**Comment by paufar** [comment]
Yes i figured, are there any plans to make them responsive?

**Comment by tomhollander** [comment]
Not in the short term. A dashboard can have lots of charts with different dimensions in a very specific layout. It's not self evident how to make an arbitrary dashboard "responsive", so we thought it would be best to let users with this requirement do their own layout management. That said, we're open to hearing ideas on how we could improve this experience.
