### ISSUE TITLE
Charts SDK depends on vulnerable version of jsonwebtoken

### ISSUE THREAD

**Issue by vs-savelich** [mongodb-js/charts-embed-sdk#76]
**Describe the bug**
Charts SDK depends on vulnerable version of jsonwebtoken package. New version of the package is available already.

**To Reproduce**
1. Run npm audit
2. See report

**Expected behavior**
No audit messages regarding Charts SDK.

**Screenshots**
![image](https://user-images.githubusercontent.com/22545114/209306048-f31d59d0-9532-41cb-957f-0699f06f152d.png)

**Desktop (please complete the following information):**
 Not relevant

**Smartphone (please complete the following information):**
 Not relevant

**Comment by kristinamongo** [comment]
Thank you @vs-savelich for reporting this issue. We have released a new version of the Charts SDK @mongodb-js/charts-embed-dom@2.3.1 with an updated version of jsonwebtoken v9.0.0
