### ISSUE TITLE
Filter data per user

### ISSUE THREAD

**Issue by sunitakodali** [mongodb-js/charts-embed-sdk#79]
Hello, 

I have created example-chart -authenticated-realm-web.
I am able to login and view chart with two login id's
australianEmployee@mongodb.com
canadianEmployee@mongodb.com

![ex1](https://user-images.githubusercontent.com/96587254/221747272-f224de50-5f6e-4047-aa75-9a15d9e62a00.png)
I want APP to filter data for each user, but I couldn't.  Could you please help with this requirement. Thanks

**Comment by kirangp** [comment]
Hi @sunitakodali, Thanks for your question. 

We do support this for both charts and dashboard embedding. More info here:
https://www.mongodb.com/docs/charts/filter-embedded-charts/#inject-user-specific-filters
https://www.mongodb.com/docs/charts/filter-embedded-dashboards/#inject-user-specific-filters

**Comment by sunitakodali** [comment]
Thanks for the response. Previously I tried with App services, but it didn't work. So, I did it with inject-user-specific-filters.
I created a chart which represents facilities from two different organizations. Now based on the organization username entry, chart should filter or show only the facilities for that particular organization. I tried below function, but it didn't work.
I have created chart from facility table which had organization username as look up field from organization table. 

 // Return a filter based on token attributes, e.g:
if(content.token.username){
return {username:content.token.username}
} else {
return false;
}

**Comment by sunitakodali** [comment]
return {userName:context.token.sub} in the place of sub if I replace with organization username like userName:"abc", it is working, but if I use userName:content.token.Username, it is throwing me error:17.

**Comment by sunitakodali** [comment]
Thank you.

**Comment by sunitakodali** [comment]
Kiran, 
I was able to filter chart data using inject user specific filters, if I have username from the table itself. If the field is lookup filed, how can I use the field as.
"return {userName:context.token.username}" - here the userName is not the lookup field. This one worked.
 I tried couple of ways with look up field, nothing is showing up.
"return {organizationId_lookup_organization_userName:context.token.username}"

**Comment by kirangp** [comment]
@sunitakodali FYI, the lookup field should work in your original question. I got some help from the dev team to find the root cause. The filter should have the full path as it is a nested field and should be under quotes. Please try and let us know if it still does not work. See below.

`"return {organizationId_lookup_organization_userName:context.token.username}"`

**Comment by mongo-J** [comment]
Basically it should follow this pattern `${lookup_field_name}.${fieldName}` for a single level lookup field. Looking at the comment above, I suspect it would be `organizationId_lookup_organization_userName.userName` or `organizationId_lookup_organization.userName` depending how you named the lookup field.

**Comment by sunitakodali** [comment]
Tried with quotes, throwing me an error.
Without quotes:

return {organizationId_lookup_organization_userName:context.token.username} - nothing showed up.
![e1](https://user-images.githubusercontent.com/96587254/222138046-87c94efc-886b-425c-a20e-03d6be66e7a1.png)

organizationId_lookup_organization_userName.userName - Showing me a syntax error. So tried, organizationId_lookup_organization_userName:username
![e2](https://user-images.githubusercontent.com/96587254/222138654-f666e712-454e-45ad-8b11-3660cd7d3a1a.png)
error code 17.

organizationId_lookup_organization.userName - showing me as syntax error.

**Comment by sunitakodali** [comment]
I figured it out. Thank you all for your time and support.
