### ISSUE TITLE
Localisation or custom labels

### ISSUE THREAD

**Issue by bde-maze** [mongodb-js/charts-embed-sdk#80]
**Is your feature request related to a problem? Please describe.**
Our platform is fully translated and would love to be able to inject our translation in all texts that the Chart exposes. Labels, legend, title and description.

**Describe the solution you'd like**
having an option/prop to specify an object with the value for each element. (where we can inject correctly translated text)

**Describe alternatives you've considered**
having a function that resolves the translation could be another way so we can also adapt to the data (for exemple transform the dayNumbers of a X axis to the translated full name of the day -> 0 === Sunday or 1 === Lundi)

**Comment by kirangp** [comment]
@bde-maze We are actively working on functionality to expose chart labels, title and descriptions for chart embedding. We will release this in the next couple of months. 
Dashboard embedding will be supported later.

**Comment by bde-maze** [comment]
That's awesome! We are really excited about this :)

Thank you.

**Comment by thxmxx** [comment]
Hey, do you have any updates or release date for this feature? Ty

**Comment by kristinamongo** [comment]
Hi @thxmxx, embedded charts customisations will be part of the next SDK release 3.2.0. We can't give an exact date yet but it is planned for early August
