### ISSUE TITLE
Provide .done callback for chart & dashboard render functions

### ISSUE THREAD

**Issue by phil-warner** [mongodb-js/charts-embed-sdk#82]
There is an inevitable delay when embedding charts and dashboards, whilst waiting firstly for a custom JWT to be created and then for the SDK to initialise the dashboard and then each chart.

I can see that there is a .catch callback for handling rendering errors. It would also be ideal to have a .done equivalent, so that I can control how the dashboard or chart is rendered. That would allow me to use my own loader gif and fade in the whole dashboard when done.

**Comment by matt-d-rat** [comment]
The `render` method returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), the [catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) callback is exposed by this interface.

You can achieve the loading scenario you describe with what is provided today:

```js
let isLoading = true;

dashboard
  .render(document.getElementById('dashboard'))
  .then(() => { isLoading = false; })
  .catch(() => window.alert('Dashboard failed to initialise'));
```

Or with async/await

```js
let isLoading = true;

try {
  await dashboard
  .render(document.getElementById('dashboard'));

  isLoading = false;
} catch(err) {
  console.error(err);
  window.alert('Dashboard failed to initialise');
}
```

**Comment by phil-warner** [comment]
That's great. Thank you Matt.
