### ISSUE TITLE
Responsive Dashboard Mobile

### ISSUE THREAD

**Issue by matheusm** [mongodb-js/charts-embed-sdk#84]
**Describe the bug**
There are no options for responsive charts inside dashboards

**To Reproduce**
just add a dashboard with many charts inside and try to resize it.

**Comment by kristinamongo** [comment]
Hi @matheusm. There are no short term plans to make the charts inside an embedded dashboard responsive as the charts themselves can have different sizes and there are multiple different layout scenarios. A workaround is to embed the charts separately and implement your own responsive behaviour. 

Also [this is being requested already on our feedback page](https://feedback.mongodb.com/forums/923524-charts/suggestions/38670904-responsive-charts), so I would suggest that you upvote the request, and add any comments if you wish. We try to prioritise highly requested features.
