### ISSUE TITLE
statistical data - yearly, monthly, weekly, daily

### ISSUE THREAD

**Issue by mohan-unify-care** [mongodb-js/charts-embed-sdk#91]
I'm aiming to generate a chart and utilize it to view yearly, monthly, weekly, and daily statistics through the Embed SDK. Despite referencing several documents related to Atlas Charts, I couldn't find information on this. 

**Can someone explain if this is possible?**

**Comment by matt-d-rat** [comment]
@mohan-unify-care GitHub issues are for reporting bugs with the embedding SDK.

For general “how to” questions, please raise your question on the [discussions](https://github.com/mongodb-js/charts-embed-sdk/discussions) page, and we would be happy to answer (that way the whole user base benefits from the knowledge sharing).
